name: Kover

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

permissions:
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"
      - uses: gradle/wrapper-validation-action@v1
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: kover
      - name: Generate coverage badge
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.COVERAGE }}
          gistID: 7af9a474143f247a1e0077a972afd904
          filename: mcx-coverage-badge.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100
