name: Kover

on:
  push:
    branches: [ main ]
    paths:
      - "gradle/**"
      - "src/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
  workflow_dispatch:

permissions:
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Measure coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: kover
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate coverage badge
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.COVERAGE }}
          gistID: 7af9a474143f247a1e0077a972afd904
          filename: mcx-coverage-badge.json
          label: Coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100
