name: Test

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/test.yml"
      - "gradle/**"
      - "packs/**"
      - "src/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/test.yml"
      - "gradle/**"
      - "packs/**"
      - "src/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
  workflow_dispatch:

permissions:
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "20"
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Test box
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Measure coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: kover
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate coverage badge
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.COVERAGE }}
          gistID: 7af9a474143f247a1e0077a972afd904
          filename: box-coverage-badge.json
          label: Coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100
      - name: Install box
        uses: gradle/gradle-build-action@v2
        with:
          arguments: installDist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Minecraft
        id: minecraft
        uses: mcenv/setup-minecraft@v3
        with:
          version: snapshot
      - name: Setup box
        run: |
          echo "${{ github.workspace }}/build/install/box/bin" >> $GITHUB_PATH
          mkdir -p ~/.box/versions/${{ steps.minecraft.outputs.version }}
          mv $MINECRAFT ~/.box/versions/${{ steps.minecraft.outputs.version }}
      - name: Test test pack
        run: |
          cd ./packs/test
          box dependencies install
          box test ${{ steps.minecraft.outputs.version }} --nogui
      - name: Test core pack
        run: |
          cd ./packs/core
          box dependencies install
          box test ${{ steps.minecraft.outputs.version }} --nogui
      - name: Upload data packs
        uses: actions/upload-artifact@v3
        with:
          name: datapacks
          path: |
            ./packs/core/.box/world/datapacks/core_main.zip
            ./packs/core/.box/world/datapacks/core_test.zip
            ./packs/test/.box/world/datapacks/test_main.zip
            ./packs/test/.box/world/datapacks/test_test.zip
          if-no-files-found: error
