name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/wrapper-validation-action@v1
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Install dist
        uses: gradle/gradle-build-action@v2
        with:
          arguments: installDist
      - name: Upload std pack
        uses: actions/upload-artifact@v3
        with:
          name: std
          path: ./src/main/resources/std/out/datapacks/std
          if-no-files-found: error
      - name: Upload test pack
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: ./src/test/resources/test/out/datapacks/test
          if-no-files-found: error
