name: Test

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/test.yml"
      - "gradle/**"
      - "packs/**"
      - "src/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/test.yml"
      - "gradle/**"
      - "packs/**"
      - "src/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
  workflow_dispatch:

permissions:
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Test mcx
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install mcx
        uses: gradle/gradle-build-action@v2
        with:
          arguments: installDist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Minecraft
        id: minecraft
        uses: mcenv/setup-minecraft@v3
        with:
          version: snapshot
      - name: Setup mcx
        run: |
          echo "${{ github.workspace }}/build/install/mcx/bin" >> $GITHUB_PATH
          mkdir -p ~/.mcx/versions/${{ steps.minecraft.outputs.version }}
          mv $MINECRAFT ~/.mcx/versions/${{ steps.minecraft.outputs.version }}
      - name: Test test pack
        run: |
          cd ./packs/test
          mcx dependencies install
          mcx test ${{ steps.minecraft.outputs.version }} --nogui
      - name: Test core pack
        run: |
          cd ./packs/core
          mcx dependencies install
          mcx test ${{ steps.minecraft.outputs.version }} --nogui
      - name: Upload data packs
        uses: actions/upload-artifact@v3
        with:
          name: datapacks
          path: |
            ./packs/core/.mcx/world/datapacks/core_main.zip
            ./packs/core/.mcx/world/datapacks/core_test.zip
            ./packs/test/.mcx/world/datapacks/test_main.zip
            ./packs/test/.mcx/world/datapacks/test_test.zip
          if-no-files-found: error
