name: Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

permissions:
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"
      - uses: gradle/wrapper-validation-action@v1
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        uses: gradle/gradle-build-action@v2
        with:
          arguments: installDist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Minecraft
        id: minecraft
        uses: mcenv/setup-minecraft@v3
        with:
          version: snapshot
      - run: echo "${{ github.workspace }}/build/install/mcx/bin" >> $GITHUB_PATH
      - name: Test
        run: |
          mkdir -p ~/.mcx/versions/${{ steps.minecraft.outputs.version }}
          mv $MINECRAFT ~/.mcx/versions/${{ steps.minecraft.outputs.version }}
          cd ./src/test/resources/test
          mcx test ${{ steps.minecraft.outputs.version }}
      - name: Upload datapacks
        uses: actions/upload-artifact@v3
        with:
          name: datapacks
          path: |
            ./src/main/resources/std/out/datapacks/std_main
            ./src/main/resources/std/out/datapacks/std_test
            ./src/test/resources/test/out/datapacks/test_main
            ./src/test/resources/test/out/datapacks/test_test
          if-no-files-found: error
