name: Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

permissions:
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"
      - uses: gradle/wrapper-validation-action@v1
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Upload std pack
        uses: actions/upload-artifact@v3
        with:
          name: std
          path: |
            ./src/main/resources/std/out/datapacks/std_main
            ./src/main/resources/std/out/datapacks/std_test
          if-no-files-found: error
      - name: Upload test pack
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: |
            ./src/test/resources/test/out/datapacks/test_main
            ./src/test/resources/test/out/datapacks/test_test
          if-no-files-found: error
